# Generated by Django 4.2.7 on 2024-02-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profile/default_image.webp', upload_to='profile/'),
        ),
    ]
