# Generated by Django 4.2.7 on 2024-02-20 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_skill_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='sochial_facebook',
            new_name='sochial_telegram',
        ),
    ]
