# Generated by Django 4.2.7 on 2024-02-21 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='other_skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='other_skill',
            field=models.ManyToManyField(blank=True, null=True, to='users.other_skill'),
        ),
    ]
